services:
  - type: web
    name: idashboard-solarbts
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: EXCEL_FILE
        value: ZTE-AIS-Gulf Solar BTS 2025 Overall Progress.xlsx
    plan: free
